import assert from "node:assert/strict";
import test from "node:test";

import {
  formatSingleGameDebugTrace,
  type SingleGameResult,
} from "../src/index.js";
import { markCardDefinitionId, markPlayerId } from "../src/domain/types.js";

test("single-game debug trace summarizes card play and effect resolution in game terms", () => {
  const result: SingleGameResult = {
    seed: 60615,
    endReason: "maxTurnsReached",
    isGameEnd: false,
    turnsElapsed: 1,
    players: [],
    winnerIds: [],
    isTie: false,
    eventLog: [
      { type: "gameInitialized" },
      {
        type: "botActionSelected",
        playerId: markPlayerId("player-1"),
        turnNumber: 1,
        actionSequence: 1,
        actionIdentity: "playCard",
      },
      {
        type: "effectAddPowerApplied",
        playerId: markPlayerId("player-1"),
        turnNumber: 1,
        actionSequence: 1,
        actionIdentity: "playCard",
        cardInstanceId: "card-7",
        definitionId: markCardDefinitionId("fixture-power-card"),
        effectId: "add_power",
        amount: 2,
        powerBefore: 0,
        powerAfter: 2,
        sourceType: "card",
      },
      {
        type: "effectChipsGained",
        playerId: markPlayerId("player-1"),
        turnNumber: 1,
        actionSequence: 1,
        actionIdentity: "playCard",
        cardInstanceId: "card-8",
        definitionId: markCardDefinitionId("fixture-chip-card"),
        effectId: "gain_chips",
        amount: 1,
        chipsBefore: 0,
        chipsAfter: 1,
        sourceType: "card",
      },
      {
        type: "marketChipsGained",
        playerId: markPlayerId("player-1"),
        turnNumber: 1,
        actionSequence: 1,
        actionIdentity: "playCard",
        cardInstanceId: "card-9",
        definitionId: markCardDefinitionId("fixture-market-card"),
        amount: 2,
        chipsBefore: 1,
        chipsAfter: 3,
      },
      {
        type: "cardMoved",
        playerId: markPlayerId("player-1"),
        turnNumber: 1,
        actionSequence: 1,
        actionIdentity: "playCard",
        cardInstanceId: "card-10",
        definitionId: markCardDefinitionId("fixture-moved-card"),
        sourceZone: "mainMarket",
        destinationZone: "player-1.discard",
        ownerBefore: "common",
        ownerAfter: markPlayerId("player-1"),
      },
      {
        type: "cardPlayed",
        playerId: markPlayerId("player-1"),
        turnNumber: 1,
        actionSequence: 1,
        actionIdentity: "playCard",
        cardInstanceId: "card-7",
        definitionId: markCardDefinitionId("fixture-power-card"),
      },
    ],
  };

  assert.equal(
    formatSingleGameDebugTrace(result, {
      cardNames: new Map([
        ["fixture-power-card", "Мощный тестовый посох"],
        ["fixture-chip-card", "Чиповый тестовый посох"],
        ["fixture-market-card", "Рыночная карта"],
        ["fixture-moved-card", "Купленная карта"],
      ]),
    }),
    [
      "Game seed 60615: maxTurnsReached after 1 turn (technical stop)",
      "",
      "Setup",
      "- Game initialized.",
      "",
      "Turn 1, Action 1 - player-1 (playCard)",
      "- Bot selected playCard.",
      "- Effect add_power from Мощный тестовый посох (card-7): player-1 power 0 -> 2.",
      "- Effect gain_chips from Чиповый тестовый посох (card-8): player-1 chips 0 -> 1.",
      "- Market chips from Рыночная карта (card-9): player-1 chips 1 -> 3.",
      "- Move: Купленная карта (card-10) main market -> player-1 discard, owner common -> player-1.",
      "- Played Мощный тестовый посох (card-7).",
    ].join("\n")
  );
});

test("single-game debug trace summarizes targeting, zone movement, defense, death, DWT, and Trophy events", () => {
  const result: SingleGameResult = {
    seed: 707,
    endReason: "deadWizardTokensExhausted",
    isGameEnd: true,
    turnsElapsed: 4,
    players: [],
    winnerIds: [],
    isTie: false,
    eventLog: [
      { type: "gameInitialized" },
      {
        type: "cardBought",
        playerId: markPlayerId("player-1"),
        turnNumber: 4,
        actionSequence: 1,
        actionIdentity: "buyMarketCard:mainMarket",
        cardInstanceId: "card-21",
        definitionId: markCardDefinitionId("fixture-market-card"),
        destination: "discard",
      },
      {
        type: "effectCardGained",
        playerId: markPlayerId("player-1"),
        turnNumber: 4,
        actionSequence: 1,
        actionIdentity: "buyMarketCard:mainMarket",
        cardInstanceId: "card-7",
        definitionId: markCardDefinitionId("fixture-gain-card"),
        targetCardInstanceId: "card-22",
        targetDefinitionId: "fixture-target-card",
        effectId: "gain_card",
        destination: "deckTop",
        sourceType: "card",
      },
      {
        type: "defenseChoiceSelected",
        playerId: markPlayerId("player-2"),
        turnNumber: 4,
        actionSequence: 2,
        actionIdentity: "playCard",
        cardInstanceId: "card-9",
        definitionId: markCardDefinitionId("fixture-defense-card"),
        effectId: "avoid_attack",
      },
      {
        type: "defenseCardMoved",
        playerId: markPlayerId("player-2"),
        turnNumber: 4,
        actionSequence: 2,
        actionIdentity: "playCard",
        cardInstanceId: "card-9",
        definitionId: markCardDefinitionId("fixture-defense-card"),
        destination: "discard",
      },
      {
        type: "effectDamageDealt",
        playerId: markPlayerId("player-2"),
        targetPlayerId: markPlayerId("player-1"),
        turnNumber: 4,
        actionSequence: 2,
        actionIdentity: "playCard",
        cardInstanceId: "card-9",
        definitionId: markCardDefinitionId("fixture-defense-card"),
        effectId: "deal_damage",
        amount: 3,
        targetLifeBefore: 2,
        targetLifeAfter: -1,
        sourceType: "card",
      },
      {
        type: "playerDied",
        playerId: markPlayerId("player-1"),
        turnNumber: 4,
        actionSequence: 2,
        actionIdentity: "playCard",
        lifeAfter: -1,
      },
      {
        type: "trophyControlChanged",
        playerId: markPlayerId("player-2"),
        targetPlayerId: markPlayerId("player-1"),
        turnNumber: 4,
        actionSequence: 2,
        actionIdentity: "playCard",
        cardInstanceId: "card-9",
        definitionId: markCardDefinitionId("fixture-defense-card"),
        effectId: "deal_damage",
        sourceType: "card",
      },
      {
        type: "deadWizardTokenGained",
        playerId: markPlayerId("player-1"),
        turnNumber: 4,
        actionSequence: 2,
        actionIdentity: "playCard",
        tokenInstanceId: "token-4",
        tokenDefinitionId: "fixture-dwt",
      },
      {
        type: "playerResurrected",
        playerId: markPlayerId("player-1"),
        turnNumber: 4,
        actionSequence: 2,
        actionIdentity: "playCard",
        amount: 20,
        lifeBefore: -1,
        lifeAfter: 20,
      },
    ],
  };

  assert.equal(
    formatSingleGameDebugTrace(result, {
      cardNames: new Map([
        ["fixture-market-card", "Рыночная карта"],
        ["fixture-gain-card", "Карта получения"],
        ["fixture-target-card", "Целевая карта"],
        ["fixture-defense-card", "Защитная карта"],
      ]),
      tokenNames: new Map([["fixture-dwt", "Жетон мертвого волшебника"]]),
    }),
    [
      "Game seed 707: deadWizardTokensExhausted after 4 turns (game end)",
      "",
      "Setup",
      "- Game initialized.",
      "",
      "Turn 4, Action 1 - player-1 (buyMarketCard:mainMarket)",
      "- Bought Рыночная карта (card-21) -> discard.",
      "- Effect gain_card from Карта получения (card-7): player-1 chooses Целевая карта (card-22) -> deckTop.",
      "",
      "Turn 4, Action 2 - player-2 (playCard)",
      "- Defense: player-2 chooses Защитная карта (card-9) for avoid_attack.",
      "- Zone move: Защитная карта (card-9) -> discard.",
      "- Damage: player-2 deals 3 to player-1 with Защитная карта (card-9) via deal_damage. Life 2 -> -1.",
      "- Death: player-1 is defeated after reaching -1 life.",
      "- Trophy: Basic Trophy moves to player-2 after defeating player-1 with Защитная карта (card-9).",
      "- DWT: player-1 gains Жетон мертвого волшебника (token-4).",
      "- Resurrection: player-1 life -1 -> 20.",
    ].join("\n")
  );
});
